apiVersion: v1
kind: Deployment
metadata:
  name: central
spec:
  containers:
  - name: central
    image: central_img_kub
    ports:
    - containerPort: 9193
    env:
    - name: spring_rabbitmq_host
    value: rabbitmq
    - name: spring_rabbitmq_port
    value: 5672
    - name: spring_rabbitmq_username
    value: guest
    - name: spring_rabbitmq_password
    value: guest