apiVersion: v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
    - containerPort: 25672
    - containerPort: 5672
    - containerPort: 15672
    env:
    - name: HOSTNAMERABBIT
    value: rabbitmq
    - name: RABBITMQ_DEFAULT_USER
    value: guest
    - name: RABBITMQ_DEFAULT_PASS
    value: guest