spring:
  application:
    name: reserva-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/reserva
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always

      continue-on-error: false

server:
  port: 9191